/**
 * Local Persistent Mesh Message Store
 *
 * Implements:
 * - Local disk persistence (survives app restart via native storage bridge)
 * - Seen-message deduplication table
 * - Message lifecycle state transitions (PENDING, FORWARDED, DELIVERED, EXPIRED)
 * - Telemetry calculation for developer & UI inspection
 */

import {NativeModules, Platform} from 'react-native';
import {
  DEFAULT_TTL,
  MeshMessage,
  MeshTelemetry,
  MessageDeliveryStatus,
  StoredMeshMessage,
} from './types';

const {ResqBleAdvertiser} = NativeModules;

interface PersistedState {
  messages: StoredMeshMessage[];
  seenIds: string[];
}

export class MeshStoreManager {
  private messagesMap = new Map<string, StoredMeshMessage>();
  private seenIds = new Set<string>();
  private isLoaded = false;
  private onStoreUpdatedCallback: (() => void) | null = null;

  /**
   * Initializes the store from local persistent disk storage.
   */
  public async initialize(): Promise<void> {
    if (this.isLoaded) return;

    try {
      if (Platform.OS === 'android' && ResqBleAdvertiser?.loadMeshStore) {
        const rawJson: string = await ResqBleAdvertiser.loadMeshStore();
        if (rawJson && rawJson.trim() !== '{}' && rawJson.trim() !== '') {
          const parsed: PersistedState = JSON.parse(rawJson);
          if (Array.isArray(parsed.messages)) {
            parsed.messages.forEach(item => {
              this.messagesMap.set(item.message.messageId, item);
            });
          }
          if (Array.isArray(parsed.seenIds)) {
            parsed.seenIds.forEach(id => this.seenIds.add(id));
          }
        }
      }
    } catch (e) {
      // In-memory fallback if file unreadable
    }

    this.isLoaded = true;
  }

  /**
   * Commits the current in-memory store to hardware disk.
   */
  private async persist(): Promise<void> {
    if (Platform.OS !== 'android' || !ResqBleAdvertiser?.saveMeshStore) {
      return;
    }

    try {
      const state: PersistedState = {
        messages: Array.from(this.messagesMap.values()),
        seenIds: Array.from(this.seenIds).slice(-1000), // Retain latest 1000 seen message IDs
      };
      await ResqBleAdvertiser.saveMeshStore(JSON.stringify(state));
    } catch (e) {
      // Disk write failure handled gracefully
    }

    if (this.onStoreUpdatedCallback) {
      this.onStoreUpdatedCallback();
    }
  }

  /**
   * Subscribes a listener to store mutation events.
   */
  public setOnUpdateListener(listener: (() => void) | null): void {
    this.onStoreUpdatedCallback = listener;
  }

  /**
   * Checks whether a message has already been received or generated by this node.
   */
  public hasSeen(messageId: string): boolean {
    return this.seenIds.has(messageId) || this.messagesMap.has(messageId);
  }

  /**
   * Marks a message ID as seen to prevent duplicate reception/processing.
   */
  public markSeen(messageId: string): void {
    this.seenIds.add(messageId);
  }

  /**
   * Stores a new outgoing message originated by this node.
   */
  public async addOutgoingMessage(message: MeshMessage): Promise<StoredMeshMessage> {
    this.seenIds.add(message.messageId);

    const stored: StoredMeshMessage = {
      message,
      status: 'PENDING',
      receivedAt: Date.now(),
      forwardedToPeers: [],
    };

    this.messagesMap.set(message.messageId, stored);
    await this.persist();
    return stored;
  }

  /**
   * Stores a newly received message from an over-the-air BLE peer.
   */
  public async addIncomingMessage(
    message: MeshMessage,
    senderAddress?: string,
    initialStatus: MessageDeliveryStatus = 'PENDING'
  ): Promise<StoredMeshMessage | null> {
    if (this.hasSeen(message.messageId)) {
      return null; // Suppress duplicate
    }

    this.seenIds.add(message.messageId);

    const stored: StoredMeshMessage = {
      message,
      status: initialStatus,
      receivedAt: Date.now(),
      forwardedToPeers: senderAddress ? [senderAddress] : [],
      lastHopSender: senderAddress,
    };

    this.messagesMap.set(message.messageId, stored);
    await this.persist();
    return stored;
  }

  /**
   * Updates message status after forwarding to a peer.
   */
  public async recordForwarded(
    messageId: string,
    peerAddress: string
  ): Promise<void> {
    const entry = this.messagesMap.get(messageId);
    if (!entry) return;

    if (!entry.forwardedToPeers.includes(peerAddress)) {
      entry.forwardedToPeers.push(peerAddress);
    }
    entry.status = 'FORWARDED';
    entry.lastAttemptAt = Date.now();
    await this.persist();
  }

  /**
   * Records a failed forwarding attempt for retry backoff.
   */
  public async recordForwardFailed(
    messageId: string,
    error: string
  ): Promise<void> {
    const entry = this.messagesMap.get(messageId);
    if (!entry) return;

    entry.lastAttemptAt = Date.now();
    entry.lastError = error;
    await this.persist();
  }

  /**
   * Marks a message as delivered at its destination.
   */
  public async markDelivered(messageId: string): Promise<void> {
    const entry = this.messagesMap.get(messageId);
    if (!entry) return;

    entry.status = 'DELIVERED';
    await this.persist();
  }

  /**
   * Marks a message as expired because TTL reached 0.
   */
  public async markExpired(messageId: string): Promise<void> {
    const entry = this.messagesMap.get(messageId);
    if (!entry) return;

    entry.status = 'EXPIRED';
    await this.persist();
  }

  /**
   * Retrieves all messages currently in PENDING state awaiting forwarding.
   */
  public getPendingMessages(): StoredMeshMessage[] {
    return Array.from(this.messagesMap.values()).filter(
      item => item.status === 'PENDING'
    );
  }

  /**
   * Retrieves all messages sorted newest first.
   */
  public getAllMessages(): StoredMeshMessage[] {
    return Array.from(this.messagesMap.values()).sort(
      (a, b) => b.receivedAt - a.receivedAt
    );
  }

  /**
   * Clears all stored messages (for developer reset/debugging).
   */
  public async clearAll(): Promise<void> {
    this.messagesMap.clear();
    this.seenIds.clear();
    if (Platform.OS === 'android' && ResqBleAdvertiser?.clearMeshStore) {
      await ResqBleAdvertiser.clearMeshStore();
    }
    if (this.onStoreUpdatedCallback) {
      this.onStoreUpdatedCallback();
    }
  }

  /**
   * Calculates live telemetry metrics.
   */
  public getTelemetry(localNodeId: string): MeshTelemetry {
    const all = Array.from(this.messagesMap.values());
    let pendingCount = 0;
    let forwardedCount = 0;
    let deliveredCount = 0;
    let expiredCount = 0;

    let lastReceived: MeshMessage | null = null;
    let lastForwarded: MeshMessage | null = null;

    all.forEach(item => {
      switch (item.status) {
        case 'PENDING':
          pendingCount++;
          break;
        case 'FORWARDED':
          forwardedCount++;
          break;
        case 'DELIVERED':
          deliveredCount++;
          break;
        case 'EXPIRED':
          expiredCount++;
          break;
      }

      if (item.message.originNodeId !== localNodeId) {
        if (!lastReceived || item.receivedAt > (lastReceived.createdAt || 0)) {
          lastReceived = item.message;
        }
      }

      if (item.status === 'FORWARDED') {
        if (!lastForwarded || (item.lastAttemptAt || 0) > (lastForwarded.createdAt || 0)) {
          lastForwarded = item.message;
        }
      }
    });

    return {
      localNodeId,
      totalMessages: all.length,
      pendingCount,
      forwardedCount,
      deliveredCount,
      expiredCount,
      lastReceivedMessage: lastReceived,
      lastForwardedMessage: lastForwarded,
    };
  }

  /**
   * Creates a standardized generic test message for Phase 4 validation.
   */
  public createTestMessage(
    originNodeId: string,
    customText?: string
  ): MeshMessage {
    const nonce = Math.floor(0x1000 + Math.random() * 0xefff)
      .toString(16)
      .toUpperCase();
    const timestamp = Date.now();
    const messageId = `${originNodeId}_${timestamp}_${nonce}`;

    return {
      messageId,
      originNodeId,
      destinationNodeId: undefined, // Broadcast flood
      messageType: 'TEST',
      createdAt: timestamp,
      ttl: DEFAULT_TTL,
      hopCount: 0,
      payload: customText || `Hello from RESQ mesh node [${originNodeId.slice(-4)}]`,
    };
  }
}

export const meshStore = new MeshStoreManager();
